<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>added_banana</name>
   <tag></tag>
   <elementGuidId>dcd9c6fb-760d-45b5-b0a8-57ddf282d5ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-product-list/div/div[2]/div/div[2]/a/div[2]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-product-list/div/div[2]/div/div[2]/a/div[2]/div[2]/button</value>
   </webElementProperties>
</WebElementEntity>
