<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>added_garden</name>
   <tag></tag>
   <elementGuidId>13af259e-be55-4ac7-a2b9-2fed952c05fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-product-list/div/div[2]/div/div[1]/a/div[2]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-product-list/div/div[2]/div/div[1]/a/div[2]/div[2]/button</value>
   </webElementProperties>
</WebElementEntity>
